CREATE TABLE "TONGRENG"."CATEGORIES"
(
"CATEGORY_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"CATEGORY_NAME" VARCHAR(100) NOT NULL,
"DESCRIPTION" CLOB,
NOT CLUSTER PRIMARY KEY("CATEGORY_ID"),
UNIQUE("CATEGORY_NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE TONGRENG.CATEGORIES IS '商品分类表';
COMMENT ON COLUMN TONGRENG.CATEGORIES."CATEGORY_ID" IS '分类ID (主键, 自增)';
COMMENT ON COLUMN TONGRENG.CATEGORIES."CATEGORY_NAME" IS '分类名称 (唯一)';
COMMENT ON COLUMN TONGRENG.CATEGORIES."DESCRIPTION" IS '分类描述';


CREATE TABLE "TONGRENG"."COMMENTS"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"PRODUCT_ID" BIGINT NOT NULL,
"USER_ID" BIGINT NOT NULL,
"CONTENT" VARCHAR(1000) NOT NULL,
"CREATED_TIME" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
"PARENT_ID" BIGINT,
NOT CLUSTER PRIMARY KEY("ID"),
FOREIGN KEY("PRODUCT_ID") REFERENCES "TONGRENG"."PRODUCTS"("PRODUCT_ID"),
FOREIGN KEY("USER_ID") REFERENCES "TONGRENG"."USERS"("USER_ID"),
FOREIGN KEY("PARENT_ID") REFERENCES "TONGRENG"."COMMENTS"("ID") ON DELETE CASCADE  WITH INDEX ) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "TONGRENG"."CONVERSATIONS"
(
"CONVERSATION_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"USER1_ID" BIGINT NOT NULL,
"USER2_ID" BIGINT NOT NULL,
"LAST_MESSAGE_TIME" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
NOT CLUSTER PRIMARY KEY("CONVERSATION_ID"),
CONSTRAINT "FK_CONV_USER1" FOREIGN KEY("USER1_ID") REFERENCES "TONGRENG"."USERS"("USER_ID"),
CONSTRAINT "FK_CONV_USER2" FOREIGN KEY("USER2_ID") REFERENCES "TONGRENG"."USERS"("USER_ID"),
CONSTRAINT "UK_CONVERSATION" UNIQUE("USER1_ID", "USER2_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE TONGRENG.CONVERSATIONS IS '用户私信会话表';
COMMENT ON COLUMN TONGRENG.CONVERSATIONS."CONVERSATION_ID" IS '会话ID (主键, 自增)';
COMMENT ON COLUMN TONGRENG.CONVERSATIONS."USER1_ID" IS '用户1ID';
COMMENT ON COLUMN TONGRENG.CONVERSATIONS."USER2_ID" IS '用户2ID';
COMMENT ON COLUMN TONGRENG.CONVERSATIONS."LAST_MESSAGE_TIME" IS '最后消息时间';


CREATE OR REPLACE  INDEX "TONGRENG"."IDX_CONVERSATION_USER1" ON "TONGRENG"."CONVERSATIONS"("USER1_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "TONGRENG"."IDX_CONVERSATION_USER2" ON "TONGRENG"."CONVERSATIONS"("USER2_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "TONGRENG"."FAVORITES"
(
"FAVORITE_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"USER_ID" BIGINT NOT NULL,
"PRODUCT_ID" BIGINT NOT NULL,
"FAVORITE_TIME" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
NOT CLUSTER PRIMARY KEY("FAVORITE_ID"),
CONSTRAINT "FK_FAVORITE_USER" FOREIGN KEY("USER_ID") REFERENCES "TONGRENG"."USERS"("USER_ID"),
CONSTRAINT "FK_FAVORITE_PRODUCT" FOREIGN KEY("PRODUCT_ID") REFERENCES "TONGRENG"."PRODUCTS"("PRODUCT_ID"),
CONSTRAINT "UK_USER_PRODUCT_FAVORITE" UNIQUE("USER_ID", "PRODUCT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE TONGRENG.FAVORITES IS '用户收藏表';
COMMENT ON COLUMN TONGRENG.FAVORITES."FAVORITE_ID" IS '收藏记录ID (主键, 自增)';
COMMENT ON COLUMN TONGRENG.FAVORITES."USER_ID" IS '用户ID (外键)';
COMMENT ON COLUMN TONGRENG.FAVORITES."PRODUCT_ID" IS '商品ID (外键)';
COMMENT ON COLUMN TONGRENG.FAVORITES."FAVORITE_TIME" IS '收藏时间';


CREATE TABLE "TONGRENG"."MESSAGES"
(
"MESSAGE_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"CONVERSATION_ID" BIGINT NOT NULL,
"SENDER_ID" BIGINT NOT NULL,
"RECEIVER_ID" BIGINT NOT NULL,
"CONTENT" VARCHAR(1000) NOT NULL,
"SEND_TIME" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
"IS_READ" NUMBER(1,0) DEFAULT 0,
NOT CLUSTER PRIMARY KEY("MESSAGE_ID"),
CONSTRAINT "FK_MESSAGE_CONV" FOREIGN KEY("CONVERSATION_ID") REFERENCES "TONGRENG"."CONVERSATIONS"("CONVERSATION_ID"),
CONSTRAINT "FK_MESSAGE_SENDER" FOREIGN KEY("SENDER_ID") REFERENCES "TONGRENG"."USERS"("USER_ID"),
CONSTRAINT "FK_MESSAGE_RECEIVER" FOREIGN KEY("RECEIVER_ID") REFERENCES "TONGRENG"."USERS"("USER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE TONGRENG.MESSAGES IS '私信消息表';
COMMENT ON COLUMN TONGRENG.MESSAGES."MESSAGE_ID" IS '消息ID (主键, 自增)';
COMMENT ON COLUMN TONGRENG.MESSAGES."CONVERSATION_ID" IS '会话ID';
COMMENT ON COLUMN TONGRENG.MESSAGES."SENDER_ID" IS '发送者ID';
COMMENT ON COLUMN TONGRENG.MESSAGES."RECEIVER_ID" IS '接收者ID';
COMMENT ON COLUMN TONGRENG.MESSAGES."CONTENT" IS '消息内容';
COMMENT ON COLUMN TONGRENG.MESSAGES."SEND_TIME" IS '发送时间';
COMMENT ON COLUMN TONGRENG.MESSAGES."IS_READ" IS '是否已读(0:未读, 1:已读)';


CREATE OR REPLACE  INDEX "TONGRENG"."IDX_MESSAGE_CONVERSATION" ON "TONGRENG"."MESSAGES"("CONVERSATION_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "TONGRENG"."IDX_MESSAGE_SENDER" ON "TONGRENG"."MESSAGES"("SENDER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "TONGRENG"."IDX_MESSAGE_RECEIVER" ON "TONGRENG"."MESSAGES"("RECEIVER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "TONGRENG"."IDX_MESSAGE_IS_READ" ON "TONGRENG"."MESSAGES"("IS_READ" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "TONGRENG"."ORDERS"
(
"ORDER_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"PRODUCT_ID" BIGINT NOT NULL,
"BUYER_ID" BIGINT NOT NULL,
"SELLER_ID" BIGINT NOT NULL,
"STATUS" VARCHAR(20) NOT NULL,
"PRICE_AT_PURCHASE" DECIMAL(10,2) NOT NULL,
"ORDER_TIME" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
"LAST_UPDATE_TIME" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
NOT CLUSTER PRIMARY KEY("ORDER_ID"),
CONSTRAINT "FK_ORDER_PRODUCT" FOREIGN KEY("PRODUCT_ID") REFERENCES "TONGRENG"."PRODUCTS"("PRODUCT_ID"),
CONSTRAINT "FK_ORDER_BUYER" FOREIGN KEY("BUYER_ID") REFERENCES "TONGRENG"."USERS"("USER_ID"),
CONSTRAINT "FK_ORDER_SELLER" FOREIGN KEY("SELLER_ID") REFERENCES "TONGRENG"."USERS"("USER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE TONGRENG.ORDERS IS '订单信息表';
COMMENT ON COLUMN TONGRENG.ORDERS."ORDER_ID" IS '订单ID (主键, 自增)';
COMMENT ON COLUMN TONGRENG.ORDERS."PRODUCT_ID" IS '商品ID (外键)';
COMMENT ON COLUMN TONGRENG.ORDERS."BUYER_ID" IS '买家用户ID (外键)';
COMMENT ON COLUMN TONGRENG.ORDERS."SELLER_ID" IS '卖家用户ID (外键)';
COMMENT ON COLUMN TONGRENG.ORDERS."STATUS" IS '订单状态 (PENDING, COMPLETED等)';
COMMENT ON COLUMN TONGRENG.ORDERS."PRICE_AT_PURCHASE" IS '下单时商品价格';
COMMENT ON COLUMN TONGRENG.ORDERS."ORDER_TIME" IS '订单创建时间';
COMMENT ON COLUMN TONGRENG.ORDERS."LAST_UPDATE_TIME" IS '订单最后更新时间';


CREATE TABLE "TONGRENG"."PRODUCTS"
(
"PRODUCT_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"USER_ID" BIGINT NOT NULL,
"CATEGORY_ID" BIGINT NOT NULL,
"TITLE" VARCHAR(200) NOT NULL,
"DESCRIPTION" CLOB,
"PRICE" DECIMAL(10,2) NOT NULL,
"STATUS" VARCHAR(20) DEFAULT 'AVAILABLE' NOT NULL,
"IMAGE_URL" VARCHAR(512),
"POST_DATE" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
"VIEWS" INT DEFAULT 0,
NOT CLUSTER PRIMARY KEY("PRODUCT_ID"),
CONSTRAINT "FK_PRODUCT_USER" FOREIGN KEY("USER_ID") REFERENCES "TONGRENG"."USERS"("USER_ID"),
CONSTRAINT "FK_PRODUCT_CATEGORY" FOREIGN KEY("CATEGORY_ID") REFERENCES "TONGRENG"."CATEGORIES"("CATEGORY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE TONGRENG.PRODUCTS IS '商品信息表';
COMMENT ON COLUMN TONGRENG.PRODUCTS."PRODUCT_ID" IS '商品ID (主键, 自增)';
COMMENT ON COLUMN TONGRENG.PRODUCTS."USER_ID" IS '发布者用户ID (外键)';
COMMENT ON COLUMN TONGRENG.PRODUCTS."CATEGORY_ID" IS '商品分类ID (外键)';
COMMENT ON COLUMN TONGRENG.PRODUCTS."TITLE" IS '商品标题';
COMMENT ON COLUMN TONGRENG.PRODUCTS."DESCRIPTION" IS '商品描述';
COMMENT ON COLUMN TONGRENG.PRODUCTS."PRICE" IS '商品价格';
COMMENT ON COLUMN TONGRENG.PRODUCTS."STATUS" IS '商品状态 (AVAILABLE, SOLD等)';
COMMENT ON COLUMN TONGRENG.PRODUCTS."IMAGE_URL" IS '商品主图片URL';
COMMENT ON COLUMN TONGRENG.PRODUCTS."POST_DATE" IS '发布时间';
COMMENT ON COLUMN TONGRENG.PRODUCTS."VIEWS" IS '浏览次数';


CREATE OR REPLACE  INDEX "TONGRENG"."IDX_PRODUCT_TITLE" ON "TONGRENG"."PRODUCTS"("TITLE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "TONGRENG"."IDX_PRODUCT_USER_ID" ON "TONGRENG"."PRODUCTS"("USER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "TONGRENG"."IDX_PRODUCT_CATEGORY_ID" ON "TONGRENG"."PRODUCTS"("CATEGORY_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "TONGRENG"."USERS"
(
"USER_ID" BIGINT IDENTITY(1, 1) NOT NULL,
"USERNAME" VARCHAR(50) NOT NULL,
"PASSWORD_HASH" VARCHAR(255) NOT NULL,
"EMAIL" VARCHAR(100) NOT NULL,
"REGISTRATION_DATE" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
"LAST_LOGIN_DATE" TIMESTAMP(6),
"AVATAR_URL" VARCHAR(512),
"BIO" VARCHAR(500),
NOT CLUSTER PRIMARY KEY("USER_ID"),
UNIQUE("USERNAME"),
UNIQUE("EMAIL")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE TONGRENG.USERS IS '用户信息表';
COMMENT ON COLUMN TONGRENG.USERS."USER_ID" IS '用户ID (主键, 自增)';
COMMENT ON COLUMN TONGRENG.USERS."USERNAME" IS '用户名 (唯一)';
COMMENT ON COLUMN TONGRENG.USERS."PASSWORD_HASH" IS '加密后的密码';
COMMENT ON COLUMN TONGRENG.USERS."EMAIL" IS '电子邮箱 (唯一)';
COMMENT ON COLUMN TONGRENG.USERS."REGISTRATION_DATE" IS '注册时间';
COMMENT ON COLUMN TONGRENG.USERS."LAST_LOGIN_DATE" IS '最后登录时间';
COMMENT ON COLUMN TONGRENG.USERS."AVATAR_URL" IS '用户头像图片URL';


